### ISSUE TITLE
Crash while clicking on note

### ISSUE THREAD

**Issue by mobitar** [standardnotes/android#13]
I'm going to try and replicate this, but just wanted to make a note of it here in case I can't. This happened when I just clicked around normally, going from note to note, etc. It finally crashed upon selecting a note.

```
FATAL EXCEPTION: main
                  Process: org.standardnotes.notes.buildfortest, PID: 10975
                  java.lang.RuntimeException: Unable to start activity ComponentInfo{org.standardnotes.notes.buildfortest/org.standardnotes.notes.NoteActivity}: java.lang.IllegalStateException: HorizontalScrollView can host only one direct child
                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2665)
                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2726)
                      at android.app.ActivityThread.-wrap12(ActivityThread.java)
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1477)
                      at android.os.Handler.dispatchMessage(Handler.java:102)
                      at android.os.Looper.loop(Looper.java:154)
                      at android.app.ActivityThread.main(ActivityThread.java:6119)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
                   Caused by: java.lang.IllegalStateException: HorizontalScrollView can host only one direct child
                      at android.widget.HorizontalScrollView.addView(HorizontalScrollView.java:225)
                      at org.standardnotes.notes.frag.NoteFragment.onViewCreated(NoteFragment.kt:51)
                      at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1315)
                      at android.support.v4.app.FragmentManagerImpl.moveFragmentsToInvisible(FragmentManager.java:2323)
                      at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2136)
                      at android.support.v4.app.FragmentManagerImpl.optimizeAndExecuteOps(FragmentManager.java:2092)
                      at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1998)
                      at android.support.v4.app.FragmentController.execPendingActions(FragmentController.java:388)
                      at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:607)
                      at android.support.v7.app.AppCompatActivity.onStart(AppCompatActivity.java:181)
                      at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1248)
                      at android.app.Activity.performStart(Activity.java:6696)
                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2628)
                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2726) 
                      at android.app.ActivityThread.-wrap12(ActivityThread.java) 
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1477) 
                      at android.os.Handler.dispatchMessage(Handler.java:102) 
                      at android.os.Looper.loop(Looper.java:154) 
                      at android.app.ActivityThread.main(ActivityThread.java:6119) 
                      at java.lang.reflect.Method.invoke(Native Method) 
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886) 
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776) 
```

**Comment by mobitar** [comment]
Strange, not it's happening consistently anytime I select a note.

**Comment by deftelf** [comment]
I see the problem. Did a silly thing.
